### PR TITLE
Use space :align-to instead of manual computations

### LINKED ISSUE #29: Right corner alignment off
I found that, for whatever reason, the line/column indicators would crop in the corners:
https://github.com/rougier/elegant-emacs/blob/2aba642522aafc915dd6375d34602de2cf50fbec/elegant.el#L155-L171

(It's probably due to a macOS and emacs 28 font rendering issue because esp. with light fonts I ran into calculation problems in the past.)

Screen Shot 2021-11-07 at 00 44 38

### PR DESCRIPTION
**Pull request by DivineDominion**
Fixes #29 

----

Looking at marginalia.el issues, code, and [the README](https://github.com/minad/marginalia/tree/main#adding-custom-annotators-or-classifiers) I found out about alignment propertization, and that fixes the problem of chopped-off characters for me:

```elisp
(defun mode-line-render (left right)
  "Function to render the modeline LEFT to RIGHT."
  (concat left
          (propertize " "
                      'display `(space :align-to (- right ,(length right))))
          right))
```

You can also easily add a middle column later if you want:

```elisp
(defun mode-line-render (left center right)
  "Function to render the modeline LEFT, CENTER, and RIGHT."
  (concat left
          (propertize " "
                      'display `(space :align-to (- center ,(length center))))
          center
          (propertize " "
                      'display `(space :align-to (- right ,(length right))))
          right))
```

With the space alignment stuff here, this even works on a **per-pixel offset basis** -- I can freely resize the window and the line and column indicators stick to the window edges.

Compare with 

    (setq frame-resize-pixelwise t)

... and you'll see that the current approach moves in units of 1 character, while this PR will move per pixel.

### CODE REVIEW

**Comment by DivineDominion** [comment]
Relevant docs:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Property.html
https://www.gnu.org/software/emacs/manual/html_node/elisp/Specified-Space.html

**Comment by rougier** [comment]
I remember having tried that but I got problem with the face using for alignment. For example, if you want to have a continuous underline, it was not working.

**Comment by DivineDominion** [comment]
@rougier Do you remember the particular setup? When I save my replacement for `mode-line-render` in elegant.el and launch `emacs -q -l sanity.el -l elegance.el Splash.org &` it looks fine.

**Comment by rougier** [comment]
Thanks. I need I'll merge. In the meantime, I'll try to adapt your code to [nano-modeline](https://github.com/rougier/nano-modeline)

**Pull request merged**
